"""empty message

Revision ID: c8b251beb0ab
Revises: 
Create Date: 2023-05-17 02:21:42.215244

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c8b251beb0ab'
down_revision = None
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('it_college', schema=None) as batch_op:
        batch_op.alter_column('id', new_column_name='old_id')

    op.add_column('it_college', sa.Column('id', sa.Integer(), nullable=False, primary_key=True))
    op.execute('UPDATE it_college SET id = CAST(old_id AS INTEGER)')
    op.drop_column('it_college', 'old_id')

    # ### end Alembic commands ###



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('it_college', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.Integer(),
                              type_=sa.VARCHAR(),
                              existing_nullable=False,
                              autoincrement=True,
                              existing_server_default=sa.text("nextval('it_college_id_seq'::regclass)"))

    # ### end Alembic commands ###
